### ISSUE TITLE
Typeahead should use the existing style

### ISSUE THREAD

**Issue by JeffreyMFarley** [cfpb/ccdb5-ui#47]
This was raised during [the PR for #40](https://github.com/cfpb/ccdb5-ui/pull/40#pullrequestreview-53735907)

## Current behavior

The UI uses the styles designed by @kurzn 

## Expected behavior

@sebworks requested the component use the existing styles from the `cfgov` site

**Comment by JeffreyMFarley** [comment]
It should also be noted that `CollapsibleFilter` uses it's own styling and not https://cfpb.github.io/capital-framework/components/cf-expandables/

**Comment by kurzn** [comment]
Here's the changes to our design for typeahead that we should use: 

Use the gray 10 for hover (to match the Ask style). Since we use that for the "continue typing" at the bottom, change that to Pacific 20. 

I will put in a request to update Ask styles to include some others from our (2px border, bolding of matched letters). The Ask style can keep the scrolling results box. We have a different use case for that. 


![image](https://user-images.githubusercontent.com/10562534/29176228-dced93bc-7db0-11e7-9bd2-f2322775fede.png)

**Comment by sephcoster** [comment]
Discovered an interesting behavior for main search type-ahead involving 5-10 bits of clear pixels inside left of the blue outline. Does not occur for filter type-aheads, just the main bar:

![screen shot 2017-08-15 at 12 04 25 pm](https://user-images.githubusercontent.com/1028659/29324449-0a1aef88-81b2-11e7-990c-b447a6dcb9b4.png)

**Comment by JeffreyMFarley** [comment]
I don't see this behavior in the development harness, is this from the cfgov-refresh version?

**Comment by sephcoster** [comment]
Yes.

**Comment by JeffreyMFarley** [comment]
The spacing is there on `http://build.consumerfinance.gov/data-research/consumer-complaints/search` but not the develpment harness

Ugh, with the focus handler, it's hard to figure out what is happening
